services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
  gateway:
    build: gateway
    depends_on:
      - auth-service
      - product-service
    ports:
      - "8080:8080"
    environment:
      AUTH_SECRET_KEY: gustavo_santos_siqueira_secret_segura
      AUTH_SERVICE_URL: http://auth-service:8080
      PRODUCT_SERVICE_URL: http://product-service:8080
  auth-service:
    build: auth
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/auth
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      AUTH_SECRET_KEY: gustavo_santos_siqueira_secret_segura
  product-service:
    build: product
    